### ISSUE TITLE
Can't retry a PR with treeclosed applied

### ISSUE THREAD

**Issue by jdm** [servo/homu#120]
With treeclosed=1000 a single PR with p=1001 that fails to land, doing `@bors-servo: retry` is ignored and no progress can be made until the tree is reopened.

**Comment by Manishearth** [comment]
I think https://github.com/servo/homu/blob/master/homu/main.py#L1226 should be a continue

**Comment by Manishearth** [comment]
#121

**Comment by edunham** [comment]
Should be fixed when #121 lands.
