### ISSUE TITLE
Need feature to pause taking new builds and finish up processing notifications

### ISSUE THREAD

**Issue by edunham** [servo/homu#129]
https://github.com/servo/saltfs/issues/179 would be fixed by a "graceful stop" type of option. 

The use case here is to be able to avoid damage when changing the config at arbitrary times. 

Need tests to see what the behavior actually is when you reload the config at arbitrary times.

**Comment by aneeshusa** [comment]
I think #118 would be a nicer solution here; ideally Buildbot should shut itself down cleanly on SIGTERM. I'd like to integrate with the system service manager (e.g. systemd) as much as possible.

**Comment by edunham** [comment]
SGTM. I made this without looking very hard for potential duplicates in order to get rid of the ancient issue. 

Closing in favor of #118.
