### ISSUE TITLE
homu should accept patches when either author or reviewer are in the reviewers list

### ISSUE THREAD

**Issue by staktrace** [servo/homu#137]
Oftentimes one of the project maintainers will have a trivial patch or a follow-up or something and just needs somebody to rubberstamp it, or have a specific not-a-reviewer person review it. (https://github.com/servo/webrender/pull/1948 is a specific example). In these instances it would be useful if homu accepted the review of a non-reviewer if the patch author is a reviewer and specifically requested the review of the non-reviewer. We have this convention for mozilla-central already; a module peer can ask a non-peer for review and it's fine to land the patch with that since presumably the peer knows what they're doing.

**Comment by mbrubeck** [comment]
Our current way of supporting this is for the author (or another reviewer) to use the `delegate=somebody` command to allow `somebody` to approve a specific pull request.

**Comment by staktrace** [comment]
Ah I didn't know about that. IMO that seems like a good enough solution. Feel free to close this issue.
