### ISSUE TITLE
Permissions checks broken on master

### ISSUE THREAD

**Issue by pietroalbini** [servo/homu#150]
After updating bors to the latest master in the rust-lang/rust repository, we saw [a](https://github.com/rust-lang/rust/pull/49158#issuecomment-374346546) [few](https://github.com/rust-lang/rust/pull/49161#issuecomment-374392560) [problems](https://github.com/rust-lang/rust/pull/49187#issuecomment-374404772):

* Users in the reviewers list could post comments without any problem
* Users in the try list received a "you're not a reviewer" message
* Normal users received both "you're not a reviewer" and "you can't use try" messages

I think the cause of that is #149. Before that PR, the `verify_auth` calls were ["configured"](https://github.com/servo/homu/blob/0979fe7151a43fabd4925187ab1f97100bf4d400/homu/main.py#L457-L465) at the start of `process_command` and then [called](
https://github.com/servo/homu/blob/0979fe7151a43fabd4925187ab1f97100bf4d400/homu/main.py#L657-L658) when they were actually needed. Instead, now the `verify_auth` calls are   [directly executed](https://github.com/servo/homu/blob/246705305e2d2ed96d1a5d6ca9c5c7ef0252b650/homu/main.py#L460-L467) at the start of `process_command`, which means bors check if the user is a reviewer even if they send a simple comment without any command.

The simple solution to this issue is to reintroduce `functools.partial` in auth checks.

cc @alexrs @jdm @alexcrichton

**Comment by alexrs** [comment]
@pietroalbini  Oh, my bad. Thanks for pointing the problem out. I'll create a PR reintroducing the `functools.partial` in auth checks and I'll try to create some tests to avoid this problem in the future.
We're working on refactoring Homu to make it testable (unfortunately, with the current code, it's really hard to test), so please, if you detect any other problem, report it!

**Comment by alexrs** [comment]
@pietroalbini I have created this PR that should solve the problem. https://github.com/servo/homu/pull/151

**Comment by pietroalbini** [comment]
Thank you so much!
