### ISSUE TITLE
homu seems to get stuck after a taskcluster-only try run

### ISSUE THREAD

**Issue by jdm** [servo/homu#191]
I have observed homu become unresponsive after a `try=windows` run for servo with nothing else running. It correctly reported a failed result, but no further jobs would start until I restarted the service on three separate occasions.

**Comment by jdm** [comment]
Observed with try=linux as well, so it's nothing windows-specific.

**Comment by SimonSapin** [comment]
This sounds similar to what https://github.com/servo/homu/pull/184 supposedly had fixed.

**Comment by jdm** [comment]
I figured out the issue - the homu toml for buildbot trychoosers looks like this:
```
[repo.servo.buildbot.try_choosers]

arm = [""]

wpt = ["linux-rel-css", "linux-rel-wpt"]

mac = [""]

magicleap = [""]

linux = [""]

windows = [""]
```
[This code](https://github.com/servo/homu/blob/2ea53e76ebac3e5fa11bc39054b3cd4c42eff607/homu/main.py#L1015-L1024) attempts to fill the builders list with the set of builders that will be used from the buildbot configuration. This set of builders gets a `status-taskcluster` entry added later, and when the github hook receives a status update, it [checks](https://github.com/servo/homu/blob/2ea53e76ebac3e5fa11bc39054b3cd4c42eff607/homu/server.py#L558) if all of the known builders have received a successful result. The `""` builder will never receive a result, so homu silently waits until it decides everything has timed out about 10 hours later.

**Comment by SimonSapin** [comment]
How come we had `[""]` there instead of `[]`?

**Comment by jdm** [comment]
Because [this jinja template code](https://github.com/servo/saltfs/blob/6de004289ff289cb909eac0df5e6389dbfa601d8/homu/files/cfg.toml#L241) always has a starting and closing quote, even if the original variables are empty sequences.
