### ISSUE TITLE
Try not using a try branch?

### ISSUE THREAD

**Issue by larsbergstrom** [servo/homu#23]
On the Servo builds, we seem to only be pushing to `auto`. The default should have been to push to `try` for try builds and `auto` for auto builds, but I suspect that our move to multi-mode (buildbot+status from appveyor) is causing us to only use `auto`. The relevant code is here:
https://github.com/servo/homu/blob/master/homu/main.py#L563-L572

This is manifesting as a LOT of failed appveyor builds, as the repeated pushes over the `auto` branch are causing enqueued builds to later fail, as `auto` has something else pushed over it by the time the appveyor queue gets to it.

@Manishearth Does this sound right?

CC: @edunham

**Comment by Manishearth** [comment]
I'm not sure if auto can conflict with other builds

**Comment by larsbergstrom** [comment]
@Manishearth Here's what I seem to be seeing from logs:

PR1 gets an `r+` and is pushed to `auto`. Buildbot starts right away, but AppVeyor still has a bunch of things in its queue, but marks that hash for a build from `auto`.

PR2 gets a `try` and is pushed to `auto`. New buildbot jobs may or may not start right away, but all of the ones for the `r+` are already going.

Appveyor now finally gets to PR1 and attempts to clone the `auto` branch, but fails to checkout the hash because PR2 has been pushed over it and the commit is gone.

Note that this race condition is harder to hit (due to fewer queued jobs - AppVeyor creates tons of trash jobs - each PR, each merge to master, two for the auto pushes) but we *have* seen it before in buildbot, but have previously just written it off to "meh, github fail."

**Comment by emilio** [comment]
Sorry, misclick :/
