### ISSUE TITLE
Homu stuck in 'try' state

### ISSUE THREAD

**Issue by KiChjang** [servo/homu#31]
When a try build fails (due to intermittents) and someone r+ it after the try failure, Homu seems to still be stuck in the 'try' state, i.e. it would display "trying commit ..." instead of "testing commit ..." when building the PR, and it would not merge the branch into master. servo/servo#10670 is an example of this behaviour.

EDIT: Using `r+ clean` does not seem to solve the problem.

**Comment by Manishearth** [comment]
You need to `try-` it. I had a PR somewhere that made `r+` imply `try-`, but it wasn't accepted upstream.

This is fixed by https://github.com/servo/homu/pull/7
