### ISSUE TITLE
Homu commenting "Test successful" twice

### ISSUE THREAD

**Issue by critiqjo** [servo/homu#33]
I have "Allowed Failures" and "Fast Finish" in my [travis build](https://github.com/critiqjo/cmark-hamlet/blob/master/.travis.yml#L10-11), which means homu is notified twice.

[PR comment](https://github.com/critiqjo/cmark-hamlet/pull/1#issuecomment-215964466)

[Cleaned-up logs.tar.gz](https://github.com/servo/homu/files/243712/logs.tar.gz) (separated the logs into an `index` and `xxNN.json` files and the json files are linked from the log lines)

**Comment by Manishearth** [comment]
Might be useful to set up homu as a status hook instead of a direct Travis hook as a quick fix

**Comment by Manishearth** [comment]
(this is a bug, though. We should ignore future webhooks. I'm not sure how well homu can work with allow_failure though)

**Comment by critiqjo** [comment]
> Might be useful to set up homu as a status hook instead of a direct Travis hook as a quick fix

How's that done? I couldn't find relevant docs, sorry! Is it a Github hook? Any downsides?

(If it is hard to set up, don't bother... That repo will be inactive for some time, and I don't really care about allow\_failures either.)

**Comment by Manishearth** [comment]
like https://github.com/servo/saltfs/blob/master/homu/cfg.toml#L131

```toml
[repo.servo.status.travis]
context = 'continuous-integration/travis-ci/pr'
```

Make sure the homu webhook in your repo settings has status ticked too.

**Comment by critiqjo** [comment]
Closing since it's not much to fret over!
