### ISSUE TITLE
Support MAINTAINERS file

### ISSUE THREAD

**Issue by cgwalters** [servo/homu#34]
Migrated from https://github.com/barosl/homu/issues/125

In practice, changing this is what is causing me to restart homu a lot.  (Which has its own problems - if we miss an event due to downtime one has to go and manually resync)

**Comment by aneeshusa** [comment]
A few thoughts:

- For Servo specifically, review privileges are global, so having a MAINTAINERS file per-repo would not work well for us; we would likely have one MAINTAINERS file in the [servo/saltfs](https://github.com/servo/saltfs/) repo. We also don't update our reviewer list very often, so this isn't a pain point for us.
- To decrease the hit on our rate limit quota, it might be possible to cache the list of reviewers in memory and update it if a PR to master updates the MAINTAINERS file; this cache would get blown away and recreated when synchronizing.

**Comment by cgwalters** [comment]
Alternatively, I suspect many users would be fine if we checked whether the approver was a collaborator: https://developer.github.com/v3/repos/collaborators/#check-if-a-user-is-a-collaborator

**Comment by Manishearth** [comment]
(Servo wouldn't -- we add collaborators for tagging and stuff but we'd prefer if homu-ing was limited to reviewers and operators)

**Comment by cgwalters** [comment]
I'm happy with https://github.com/servo/homu/pull/77
