### ISSUE TITLE
commit message rewriting breaks with signed commits

### ISSUE THREAD

**Issue by cgwalters** [servo/homu#79]
See https://github.com/projectatomic/docker-storage-setup/pull/179 ➡️ https://github.com/projectatomic/docker-storage-setup/commit/f7a37469b09b841e630f06e4c149fae345f66fbd

**Comment by cgwalters** [comment]
From a quick google search:

http://stackoverflow.com/questions/31552774/unexpected-behavior-with-git-filter-branch-and-signed-commits
https://www.spinics.net/lists/git/msg256557.html

**Comment by Manishearth** [comment]
I was going to say that we never call `git-filter-branch` directly, and `rebase` handles this, so it's probably a bug in a git python lib we use, but it turns out we _do_ use `filter-branch` 😄

**Comment by cgwalters** [comment]
Our previous Homu instance was on Fedora 23 (yes really) with an old `git`, but our new one (f25) has a version of git which has the fix for this.

So yes, anyone who hits this - upgrade your git.
