### ISSUE TITLE
Don't abbreviate commit hashes in Homu's comments

### ISSUE THREAD

**Issue by nox** [servo/homu#80]
Abbreviating them can be ambiguous, cf. https://github.com/servo/servo/pull/14959#issuecomment-271921909

**Comment by Manishearth** [comment]
In fact, Github will abbreviate them anyway (but linkify correctly) if you
include them in full, so there's no reason for us to muck with this in the
first place.

-Manish Goregaokar

**Comment by Eh2406** [comment]
I can help, but am new to the codebase, where to we "muck with this"? :-)
